azimzada.com/Areas/Admin/Controllers/ExperenciesController.cs
using azimzada.com.Data;
using azimzada.com.Models;
using Microsoft.AspNetCore.Mvc;

namespace azimzada.com.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ExperenciesController : Controller
    {
        private readonly ILogger<ExperenciesController> _logger;
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _env;
        public ExperenciesController(ILogger<ExperenciesController> logger, AppDbContext context, IWebHostEnvironment env)
        {
            _logger = logger;
            _context = context;
            _env = env;
        }
        public IActionResult Index()
        {
            var workExpre = _context.Works.OrderByDescending(x => x.Id).ToList();
            return View(workExpre);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(string name, string description, DateTime startingDate, DateTime endingDate, string url, IFormFile photo)
        {

            Work work = new Work();

            if (photo != null)
            {
                var path = "/uploads/" + Guid.NewGuid() + photo.FileName;
                using (var fileStream = new FileStream(_env.WebRootPath + path, FileMode.Create))
                {
                    photo.CopyTo(fileStream);
                }
                work.Input = path;
            }
            else
            {
                work.Input = "";
            }
            work.Name = name;
            work.Description = description;
            work.StartingDate = startingDate;
            work.EndingDate = endingDate;
            if (work.Url != null)
            {
                work.Url = null;
            }
            else
            {
                work.Url = url;
            }
            _context.Works.Add(work);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Delete(int id)
        {

            var delete = _context.Works.FirstOrDefault(x => x.Id == id);
            return View(delete);
        }
        [HttpPost]
        public IActionResult Delete(Work work)
        {
            var delet = _context.Works.FirstOrDefault(x => x.Id == work.Id);
            _context.Works.Remove(delet);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Detail(int id)
        {
            var detail = _context.Works.FirstOrDefault(x => x.Id == id);
            return View(detail);
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

azimzada.com/Areas/Admin/Views/Experencies/Delete.cshtml
@model Work
<div class="container">
<div class="col-xxl">
    <div class="card mb-4">
        <div class="card-header d-flex align-items-center justify-content-between">
            <h5 class="mb-0">Basic Layout</h5>
            <small class="text-muted float-end">Default label</small>
        </div>
        <div class="card-body">
            <form method="post" asp-controller="Experencies" asp-action="Delete">
                <div class="row mb-3">
                    <label class="col-sm-2 col-form-label">Title</label>
                    <div class="col-sm-10">
                        <input type="text" readonly  class="form-control disabled "  placeholder="@Model.Name">
                    </div>
                </div>
                <div class="row mb-3">
                    <label class="col-sm-2 col-form-label">Content</label>
                    <div class="col-sm-10">
                        <textarea readonly class="form-control bg-info"
                            placeholder="@Model.Description?"
                            aria-label="@Model.Description">
                        </textarea>
                    </div>
                </div>
                <div class="row justify-content-end">
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-primary">Send</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
</div

azimzada.com/Areas/Admin/Views/Experencies/Detail.cshtml
@model Work
<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4">
        <span class="text-muted fw-light">Experencies/</span> Deteil / @Model.Id 
        <span>
            <a class="btn btn-primary active w-100" href="/Admin/Experencies/Index">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-left" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M6 12.5a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5h-8a.5.5 0 0 0-.5.5v2a.5.5 0 0 1-1 0v-2A1.5 1.5 0 0 1 6.5 2h8A1.5 1.5 0 0 1 16 3.5v9a1.5 1.5 0 0 1-1.5 1.5h-8A1.5 1.5 0 0 1 5 12.5v-2a.5.5 0 0 1 1 0v2z" />
                    <path fill-rule="evenodd" d="M.146 8.354a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L1.707 7.5H10.5a.5.5 0 0 1 0 1H1.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3z" />
                </svg> Back
            </a>
        </span>
    </h4>


    <div class="row">
        <!-- Vertical Scrollbar -->
        <div class="col-md-6 col-sm-12">
            <div class="card overflow-hidden mb-4" style="height: 300px">
                <h5 class="card-header">Content </h5>
                <div class="card-body ps ps--active-y" id="vertical-example">
                    <p>
                        @Model.Description
                    </p>
                    <div class="ps__rail-x" style="left: 0px; bottom: 0px;">
                        <div class="ps__thumb-x" tabindex="0" style="left: 0px; width: 0px;"></div>
                    </div>
                    <div class="ps__rail-y" style="top: 0px; height: 232px; right: 0px;">
                        <div class="ps__thumb-y" tabindex="0" style="top: 0px; height: 45px;"></div>
                    </div>
                </div>
            </div>
        </div>
        <!--/ Vertical Scrollbar -->
        <!-- Horizontal Scrollbar -->
        <div class="col-md-6 col-sm-12">
            <div class="card overflow-hidden mb-4" style="height: 300px">
                <h5 class="card-header">File</h5>
                <div class="card-body ps ps--active-x" id="horizontal-example">
                    <div class="row">
                        @if (Model.Input != "")
                        {
                            <div class="col-6">
                                <iframe src="@Model.Input" frameborder="0"></iframe>
                            </div>
                            <div class="col-6">

                                <a href="@Model.Input" target="_blank" class="link-dark">
                                    <button type="button" class="btn btn-primary d-block active" autocomplete="off"
                                        aria-pressed="true">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                         class="bi bi-box-arrow-up-right" viewBox="0 0 16 16">
                                            <path fill-rule="evenodd"
                                              d="M8.636 3.5a.5.5 0 0 0-.5-.5H1.5A1.5 1.5 0 0 0 0 4.5v10A1.5 1.5 0 0 0 1.5 16h10a1.5 1.5 0 0 0 1.5-1.5V7.864a.5.5 0 0 0-1 0V14.5a.5.5 0 0 1-.5.5h-10a.5.5 0 0 1-.5-.5v-10a.5.5 0 0 1 .5-.5h6.636a.5.5 0 0 0 .5-.5z" />
                                            <path fill-rule="evenodd"
                                              d="M16 .5a.5.5 0 0 0-.5-.5h-5a.5.5 0 0 0 0 1h3.793L6.146 9.146a.5.5 0 1 0 .708.708L15 1.707V5.5a.5.5 0 0 0 1 0v-5z" />
                                        </svg> Look
                                    </button>
                                </a>
                            </div>
                        }
                        else
                        {
                            <div class="container d-flex align-items-center justify-content-center">
                                <iframe src="https://www.animatedimages.org/data/media/942/animated-anime-image-0199.gif"
                                    frameborder="0"></iframe>
                            </div>
                            <div class="alert alert-primary" role="alert">File empty </div>
                        }
                    </div>
                    <div class="ps__rail-x" style="width: 681px; left: 0px; bottom: 0px;">
                        <div class="ps__thumb-x" tabindex="0" style="left: 0px; width: 236px;"></div>
                    </div>
                    <div class="ps__rail-y" style="top: 0px; right: 0px;">
                        <div class="ps__thumb-y" tabindex="0" style="top: 0px; height: 0px;"></div>
                    </div>
                </div>
            </div>
        </div>
        <!--/ Horizontal Scrollbar -->
        <!-- Vertical & Horizontal Scrollbars -->
        <div class="col-12">
            <div class="card overflow-hidden" style="height: 500px">
                <h5 class="card-header">@Model.Name - Details</h5>
                <div class="card-body ps ps--active-x ps--active-y" id="both-scrollbars-example">
                    <div class="row">
                        <div class="col-6">
                            <b>
                                Date Time
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                     fill="currentColor" class="bi bi-calendar-day" viewBox="0 0 16 16">
                                    <path d="M4.684 11.523v-2.3h2.261v-.61H4.684V6.801h2.464v-.61H4v5.332h.684zm3.296 0h.676V8.98c0-.554.227-1.007.953-1.007.125 0 .258.004.329.015v-.613a1.806 1.806 0 0 0-.254-.02c-.582 0-.891.32-1.012.567h-.02v-.504H7.98v4.105zm2.805-5.093c0 .238.192.425.43.425a.428.428 0 1 0 0-.855.426.426 0 0 0-.43.43zm.094 5.093h.672V7.418h-.672v4.105z" />
                                    <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zM1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4H1z" />
                                </svg> :
                            </b> <span>@Model.StartingDate</span>
                        </div>

                        <div class="col-6 end">
                            <b>
                                End Time
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                     fill="currentColor" class="bi bi-calendar-day" viewBox="0 0 16 16">
                                    <path d="M4.684 11.523v-2.3h2.261v-.61H4.684V6.801h2.464v-.61H4v5.332h.684zm3.296 0h.676V8.98c0-.554.227-1.007.953-1.007.125 0 .258.004.329.015v-.613a1.806 1.806 0 0 0-.254-.02c-.582 0-.891.32-1.012.567h-.02v-.504H7.98v4.105zm2.805-5.093c0 .238.192.425.43.425a.428.428 0 1 0 0-.855.426.426 0 0 0-.43.43zm.094 5.093h.672V7.418h-.672v4.105z" />
                                    <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zM1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4H1z" />
                                </svg> :
                            </b> <span>@Model.EndingDate</span>
                        </div>
                        <hr>
                        <div class="col-6">
                            @if (Model.Url != null)
                            {
                                <div class="mb-3">
                                    <label class="form-label">Url</label>
                                    <input class="form-control" type="text" placeholder="@Model.Url" readonly="">
                                </div>
                            }
                            else
                            {
                                <div class="alert alert-primary w-100" role="alert">File empty </div>
                                <div class="mb-3">
                                    <iframe src="https://www.animatedimages.org/data/media/942/animated-anime-image-0051.gif"
                                        frameborder="0" style="border: none;" scrolling="no"></iframe>
                                </div>
                            }
                        </div>
                    </div>
                    <div class="ps__rail-x" style="width: 1388px; left: 0px; bottom: 0px;">
                        <div class="ps__thumb-x" tabindex="0" style="left: 0px; width: 980px;"></div>
                    </div>
                    <div class="ps__rail-y" style="top: 0px; height: 432px; right: 0px;">
                        <div class="ps__thumb-y" tabindex="0" style="top: 0px; height: 143px;"></div>
                    </div>
                </div>
            </div>
        </div>
        <!--/ Vertical & Horizontal Scrollbars -->
    </div>
</div>

azimzada.com/Areas/Admin/Views/Experencies/Index.cshtml
@model List<Work>
<div class="container">
    <!-- Bootstrap Dark Table -->
    <hr>
    <a href="/admin/experencies/create">
        <button class="btn btn-primary btn-lg w-100" type="button">Create</button>
    </a>
    <div class="card">
        <h5 class="card-header">WORK
            EXPERIENCES </h5>
        <div class="table-responsive text-nowrap">
            <table class="table table-dark">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Title</th>
                        <th>Description</th>
                        <th>StartingDate - finish Date</th>
                        <th>Url</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody class="table-border-bottom-0">
                    @foreach (var work in Model)
                    {
                        <tr>
                            <td>
                                @work.Id
                            </td>
                            <td><i class="fab fa-angular fa-lg text-danger me-3"></i> <strong>@work.Name</strong></td>
                            <td>
                                @Html.Raw(work.Description)
                            </td>
                            <td>
                                <span> @work.StartingDate.ToString("dd.MM.yyyy " ) </span>
                                <span>
                                    @work.EndingDate.ToString()
                                </span>
                            </td>

                            <td>
                                <a  href="@work.Url" class=""><span class="badge bg-label-primary me-1">
                                        Link
                                    </span>
                                </a>
                            </td>
                            <td>
                                <div class="dropdown">
                                    <button type="button" class="btn p-0 dropdown-toggle hide-arrow"
                                        data-bs-toggle="dropdown">
                                        <i class="bx bx-dots-vertical-rounded"></i>
                                    </button>
                                    <div class="dropdown-menu">
                                        <a class="dropdown-item" href="javascript:void(0);"><i
                                                class="bx bx-edit-alt me-1"></i> Edit</a>
                                        <a class="dropdown-item text-danger" href="/admin/experencies/delete/@work.Id"><i class="bx bx-trash me-1"></i>
                                            Delete</a>
                                        <a class="dropdown-item" href="/admin/experencies/Detail/@work.Id"><i class="bx bx-detail me-1"></i>
                                            Detail</a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <!--/ Bootstrap Dark Table -->
</div>